name: 'Deploy'

on:
  push:
    branches: ['master']
jobs:
  publish:
    name: 'Publish'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Print package name
        run: echo Publishing sveltekit-adapter-aws
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@efebia-com'
      - name: Build package
        run: |
          yarn
          yarn build
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          printf "\nnpmAuthToken: ${NODE_AUTH_TOKEN}\n" >> .yarnrc.yml
          yarn npm publish
